version: '3.7'
services:
  # Tornado server
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
  # Database
  mongodb:
    image: mongo
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb
volumes:
  db-data:
  mongo-config: